// <auto-generated />
using System;
using HexagonalTemplate.Infrastructure.PgSql.Databases.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HexagonalTemplate.Infrastructure.PgSql.Databases.Migrations
{
    [DbContext(typeof(FinanceManagementContext))]
    [Migration("20250623224958_ConfigureViews")]
    partial class ConfigureViews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HexagonalTemplate.Core.Application.Contracts.ViewModel+BalanceViewModel", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Expense")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Income")
                        .HasColumnType("numeric");

                    b.ToTable((string)null);

                    b.ToView("BalanceViewModel", (string)null);
                });

            modelBuilder.Entity("HexagonalTemplate.Core.Application.Contracts.ViewModel+CategoryViewModel", b =>
                {
                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CategoryLimit")
                        .HasColumnType("numeric");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .IsUnicode(false)
                        .HasColumnType("character varying(1024)");

                    b.ToTable((string)null);

                    b.ToView("CategoryViewModel", (string)null);
                });

            modelBuilder.Entity("HexagonalTemplate.Core.Application.Contracts.ViewModel+TransactionViewModel", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .IsUnicode(false)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .IsUnicode(false)
                        .HasColumnType("character varying(1024)");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.ToTable((string)null);

                    b.ToView("TransactionViewModel", (string)null);
                });

            modelBuilder.Entity("HexagonalTemplate.Core.Domain.Modules.Accounts.Aggregates.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("HexagonalTemplate.Core.Domain.Modules.Accounts.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .IsUnicode(false)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .IsUnicode(false)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .IsUnicode(false)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Profile", (string)null);
                });

            modelBuilder.Entity("HexagonalTemplate.Core.Domain.Modules.Budgets.Aggregates.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReferencePeriod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Budget", (string)null);
                });

            modelBuilder.Entity("HexagonalTemplate.Core.Domain.Modules.Accounts.Aggregates.Account", b =>
                {
                    b.OwnsOne("HexagonalTemplate.Core.Domain.Modules.Accounts.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .IsUnicode(false)
                                .HasColumnType("character varying(1024)");

                            b1.Property<string>("Complement")
                                .HasMaxLength(1024)
                                .IsUnicode(false)
                                .HasColumnType("character varying(1024)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .IsUnicode(false)
                                .HasColumnType("character varying(1024)");

                            b1.Property<int?>("Number")
                                .HasColumnType("integer");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .IsUnicode(false)
                                .HasColumnType("character varying(1024)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .IsUnicode(false)
                                .HasColumnType("character varying(1024)");

                            b1.Property<string>("ZepCode")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .IsUnicode(false)
                                .HasColumnType("character varying(1024)");

                            b1.HasKey("Id");

                            b1.HasIndex("AccountId")
                                .IsUnique();

                            b1.ToTable("Address", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("HexagonalTemplate.Core.Domain.Modules.Accounts.Entities.Profile", b =>
                {
                    b.HasOne("HexagonalTemplate.Core.Domain.Modules.Accounts.Aggregates.Account", "Account")
                        .WithOne("Profile")
                        .HasForeignKey("HexagonalTemplate.Core.Domain.Modules.Accounts.Entities.Profile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("HexagonalTemplate.Core.Domain.Modules.Budgets.Aggregates.Budget", b =>
                {
                    b.OwnsMany("HexagonalTemplate.Core.Domain.Modules.Budgets.ValueObjects.Category", "Categories", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("BudgetId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Limit")
                                .HasColumnType("numeric");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .IsUnicode(false)
                                .HasColumnType("character varying(1024)");

                            b1.HasKey("Id");

                            b1.HasIndex("BudgetId");

                            b1.ToTable("Category", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BudgetId");

                            b1.OwnsMany("HexagonalTemplate.Core.Domain.Modules.Budgets.ValueObjects.Transaction", "Transactions", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("CategoryId")
                                        .HasColumnType("integer");

                                    b2.Property<DateTime>("CreateAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasMaxLength(1024)
                                        .IsUnicode(false)
                                        .HasColumnType("character varying(1024)");

                                    b2.Property<decimal>("Value")
                                        .HasColumnType("numeric");

                                    b2.HasKey("Id");

                                    b2.HasIndex("CategoryId");

                                    b2.ToTable("Transaction", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("CategoryId");
                                });

                            b1.Navigation("Transactions");
                        });

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("HexagonalTemplate.Core.Domain.Modules.Accounts.Aggregates.Account", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
